### ISSUE TITLE
还不太明白怎么使用。

### ISSUE THREAD

**Issue by fanghongxing** [ennnnny/typecho#1]
RT！小白目前还不怎么搞得懂该怎么用……笑cry

**Comment by ennnnny** [comment]
这个项目里面有两个插件...你是哪个插件不知道怎么使用？

**Comment by fanghongxing** [comment]
CommentApprove for typecho这一个，不知道加在comments文件哪里。n(*≧▽≦*)n

**Comment by fanghongxing** [comment]
懂了懂了。之前加进去没效果以为是加的地方错了。原来把$this改为$comments就好了……(*^__^*) 嘻嘻……

**Comment by ennnnny** [comment]
可以了就行 : ) 
用$this或用$comments是看模板的，每个人不一样的。

**Comment by fanghongxing** [comment]
嗯嗯。谢谢……
