### ISSUE TITLE
不登陆的用户似乎不会显示？

### ISSUE THREAD

**Issue by if1y** [ennnnny/typecho#2]
使用发现只有作者才会显示。。。不知道哪里搞错了

**Comment by ennnnny** [comment]
应该是你放的位置不对吧，如果可以，把代码截图看下

**Comment by if1y** [comment]
> 应该是你放的位置不对吧，如果可以，把代码截图看下

https://gist.github.com/kiwiape/8d2d55ebd0e7ca5800bf7eb39755b73a
comments.php 代码已附上，我加在29行了

**Comment by ennnnny** [comment]
从代码的26行可以看到，你是放到if条件里面了。那个条件是判断当前用户是否就是该文章的用户，如果是，下面是显示Author标志。你加的位置不对，你加在30行跟31行之间试试。

**Comment by if1y** [comment]
确实，经过调整已经正常了。感谢大佬抽空解答 👍 
（个人不是特别懂代码，所以只是看着加的，忽略了if条件，这下明白啦）
